# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Study log'
description:      'JunHyun Lee'
#url:              http://127.0.0.1:4000
url:              http://leejunhyun.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
favicon:
author:
  name:           'JunHyun Lee'
  url:            

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

disqus:
  shortname: junhyun-blog
google_analytics: 'UA-125030638-1'
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
# Custom vars
sidebar_home_link:  true

# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/LeeJunHyun/

facebook:           https://www.facebook.com/leejunhyunkorea

linkedin:           https://www.linkedin.com/in/leejunhyun

youtube:            https://www.youtube.com/channel/UCxq7PSbxVYLC2xOHOARtK3A